name: breaking-change
description: Automatically apply the label and comment needed to ensure breaking changes are documented properly when the 'breaking-change' label is applied.
resource: repository
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Add breaking change doc instructions to issue
      if:
      - payloadType: Issues
      - labelAdded:
          label: breaking-change
      then:
      - addReply:
          reply: Refer to the [.NET SDK breaking change guidelines](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/breaking-change-guidelines.md#required-process-for-all-net-sdk-breaking-changes)
    - description: Add breaking change instructions to PR
      if:
      - payloadType: Pull_Request
      - labelAdded:
          label: breaking-change
      then:
      - addLabel:
          label: needs-breaking-change-doc-created
      - addReply:
          reply: "Added `needs-breaking-change-doc-created` label because this PR\
            \ has the `breaking-change` label. \n\n\nWhen you commit this breaking\
            \ change:\n\n\n1. [ ] Create and link to this PR and the issue a matching\
            \ issue in the dotnet/docs repo using the [breaking change documentation\
            \ template](https://aka.ms/dotnet/docs/new-breaking-change-issue), then\
            \ remove this `needs-breaking-change-doc-created` label.\n\n2. [ ] Ask\
            \ a committer to mail the `.NET SDK Breaking Change Notification` email\
            \ list.\n\n\nYou can refer to the [.NET SDK breaking change guidelines](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/breaking-change-guidelines.md)"
