# Branches that trigger a build on commit
trigger:
- main
- release/*
- features/*
- 2.9.x

# Branch(es) that trigger(s) build(s) on PR
pr:
- main
- release/*
- features/*
- 2.9.x

jobs:
- job: Performance
  strategy:
    maxParallel: 4
    matrix:
      Release:
        _configuration: Release
        _codeCoverage: False
  pool:
    name: Hosted VS2017
    queue: Windows.10.Amd64.20H2.Owl.Perf
  timeoutInMinutes: 120

  steps:
    - checkout: self
      clean: true
    - task: PowerShell@2
      displayName: Restore
      inputs:
        filePath: eng\common\build.ps1
        arguments: -configuration Release -prepareMachine -ci -restore -binaryLog
    - pwsh: eng\perf\PerfCore.ps1 -v diag -diff -ci 
      displayName: Validate Performance
    - task: PublishBuildArtifacts@1
      displayName: Publish Performance Results
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts'
        ArtifactName: 'Windows Performance Results'
      continueOnError: true
      condition: always()

