' <auto-generated />
' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

Imports System
Imports System.Diagnostics

Namespace Global.Roslyn.Utilities
    <AttributeUsage(AttributeTargets.Field Or AttributeTargets.Method Or AttributeTargets.Parameter Or AttributeTargets.Property Or AttributeTargets.ReturnValue, AllowMultiple:=False, Inherited:=True)>
    Friend NotInheritable Class AsyncEntryAttribute
        Inherits Attribute
    End Class
End Namespace
