// <auto-generated />
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;

namespace Roslyn.Utilities
{
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Method | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = true)]
    internal sealed class NoMainThreadDependencyAttribute : Attribute
    {
        /// <summary>
        /// <para>Gets or sets a value indicating whether the task is always completed.</para>
        /// <para>The default value is <see langword="false"/>.</para>
        /// </summary>
        public bool AlwaysCompleted { get; set; }

        /// <summary>
        /// <para>Gets or sets a value indicating whether the dependency claim further depends on the current context at
        /// method entry. Such operations only have no main thread dependency if they are invoked from a background
        /// thread.</para>
        /// <para>The default value is <see langword="false"/>.</para>
        /// </summary>
        public bool CapturesContext { get; set; }

        /// <summary>
        /// <para>Gets or sets a value indicating whether the dependency claim applies only when the target instance of
        /// the operation is marked as not having a main thread dependency.</para>
        /// <para>The default value is <see langword="false"/>.</para>
        /// </summary>
        public bool PerInstance { get; set; }

        /// <summary>
        /// <para>Gets or sets a value indicating whether the dependency claim has been verified against the signatures
        /// and contracts of referenced code.</para>
        /// <para>The default value is <see langword="true"/>.</para>
        /// </summary>
        public bool Verified { get; set; } = true;
    }
}
