' <auto-generated />
' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

Imports System
Imports System.Diagnostics

Namespace Global.Roslyn.Utilities
    <AttributeUsage(AttributeTargets.Field Or AttributeTargets.Method Or AttributeTargets.Parameter Or AttributeTargets.Property Or AttributeTargets.ReturnValue, AllowMultiple:=False, Inherited:=True)>
    Friend NotInheritable Class NoMainThreadDependencyAttribute
        Inherits Attribute

        ''' <summary>
        ''' <para>Gets or sets a value indicating whether the task is always completed.</para>
        ''' <para>The default value is <see langword="False"/>.</para>
        ''' </summary>
        Public Property AlwaysCompleted As Boolean

        ''' <summary>
        ''' <para>Gets or sets a value indicating whether the dependency claim further depends on the current context at
        ''' method entry. Such operations only have no main thread dependency if they are invoked from a background
        ''' thread.</para>
        ''' <para>The default value is <see langword="False"/>.</para>
        ''' </summary>
        Public Property CapturesContext As Boolean

        ''' <summary>
        ''' <para>Gets or sets a value indicating whether the dependency claim applies only when the target instance of
        ''' the operation is marked as not having a main thread dependency.</para>
        ''' <para>The default value is <see langword="False"/>.</para>
        ''' </summary>
        Public Property PerInstance As Boolean

        ''' <summary>
        ''' <para>Gets or sets a value indicating whether the dependency claim has been verified against the signatures
        ''' and contracts of referenced code.</para>
        ''' <para>The default value is <see langword="True"/>.</para>
        ''' </summary>
        Public Property Verified As Boolean = True
    End Class
End Namespace
