//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Runtime.Analyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemRuntimeAnalyzersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemRuntimeAnalyzersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Runtime.Analyzers.SystemRuntimeAnalyzersResources", typeof(SystemRuntimeAnalyzersResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string literal parameter of an attribute does not parse correctly for a URL, a GUID, or a version..
        /// </summary>
        internal static string AttributeStringLiteralsShouldParseCorrectlyDescription {
            get {
                return ResourceManager.GetString("AttributeStringLiteralsShouldParseCorrectlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the constructor of {0}, change the value of argument {1}, which is currently &quot;{2}&quot;, to something that can be correctly parsed as {3}..
        /// </summary>
        internal static string AttributeStringLiteralsShouldParseCorrectlyMessageDefault {
            get {
                return ResourceManager.GetString("AttributeStringLiteralsShouldParseCorrectlyMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the constructor of {0}, change the value of argument {1}, which is currently an empty string (&quot;&quot;), to something that can be correctly parsed as {2}..
        /// </summary>
        internal static string AttributeStringLiteralsShouldParseCorrectlyMessageEmpty {
            get {
                return ResourceManager.GetString("AttributeStringLiteralsShouldParseCorrectlyMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute string literals should parse correctly.
        /// </summary>
        internal static string AttributeStringLiteralsShouldParseCorrectlyTitle {
            get {
                return ResourceManager.GetString("AttributeStringLiteralsShouldParseCorrectlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Framework class library provides methods for retrieving custom attributes. By default, these methods search the attribute inheritance hierarchy. Sealing the attribute eliminates the search through the inheritance hierarchy and can improve performance..
        /// </summary>
        internal static string AvoidUnsealedAttributesDescription {
            get {
                return ResourceManager.GetString("AvoidUnsealedAttributesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid unsealed attributes.
        /// </summary>
        internal static string AvoidUnsealedAttributesMessage {
            get {
                return ResourceManager.GetString("AvoidUnsealedAttributesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid unsealed attributes.
        /// </summary>
        internal static string AvoidUnsealedAttributesTitle {
            get {
                return ResourceManager.GetString("AvoidUnsealedAttributesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #N/A.
        /// </summary>
        internal static string AvoidZeroLengthArrayAllocationsDescription {
            get {
                return ResourceManager.GetString("AvoidZeroLengthArrayAllocationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid zero-length array allocations..
        /// </summary>
        internal static string AvoidZeroLengthArrayAllocationsMessage {
            get {
                return ResourceManager.GetString("AvoidZeroLengthArrayAllocationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid zero-length array allocations..
        /// </summary>
        internal static string AvoidZeroLengthArrayAllocationsTitle {
            get {
                return ResourceManager.GetString("AvoidZeroLengthArrayAllocationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globalization.
        /// </summary>
        internal static string CategoryGlobalization {
            get {
                return ResourceManager.GetString("CategoryGlobalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        internal static string CategoryMobility {
            get {
                return ResourceManager.GetString("CategoryMobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string CategoryPerformance {
            get {
                return ResourceManager.GetString("CategoryPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability.
        /// </summary>
        internal static string CategoryReliability {
            get {
                return ResourceManager.GetString("CategoryReliability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string CategorySecurity {
            get {
                return ResourceManager.GetString("CategorySecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string CategoryUsage {
            get {
                return ResourceManager.GetString("CategoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type that implements System.IDisposable declares fields that are of types that also implement IDisposable. The Dispose method of the field is not called by the Dispose method of the declaring type..
        /// </summary>
        internal static string DisposableFieldsShouldBeDisposedDescription {
            get {
                return ResourceManager.GetString("DisposableFieldsShouldBeDisposedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable fields should be disposed.
        /// </summary>
        internal static string DisposableFieldsShouldBeDisposedMessage {
            get {
                return ResourceManager.GetString("DisposableFieldsShouldBeDisposedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable fields should be disposed.
        /// </summary>
        internal static string DisposableFieldsShouldBeDisposedTitle {
            get {
                return ResourceManager.GetString("DisposableFieldsShouldBeDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type that implements System.IDisposable and has fields that suggest the use of unmanaged resources does not implement a finalizer, as described by Object.Finalize..
        /// </summary>
        internal static string DisposableTypesShouldDeclareFinalizerDescription {
            get {
                return ResourceManager.GetString("DisposableTypesShouldDeclareFinalizerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable types should declare finalizer.
        /// </summary>
        internal static string DisposableTypesShouldDeclareFinalizerMessage {
            get {
                return ResourceManager.GetString("DisposableTypesShouldDeclareFinalizerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable types should declare finalizer.
        /// </summary>
        internal static string DisposableTypesShouldDeclareFinalizerTitle {
            get {
                return ResourceManager.GetString("DisposableTypesShouldDeclareFinalizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a type inherits from a disposable type, it must call the Dispose method of the base type from its own Dispose method..
        /// </summary>
        internal static string DisposeMethodsShouldCallBaseClassDisposeDescription {
            get {
                return ResourceManager.GetString("DisposeMethodsShouldCallBaseClassDisposeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Methods Should Call Base Class Dispose.
        /// </summary>
        internal static string DisposeMethodsShouldCallBaseClassDisposeMessage {
            get {
                return ResourceManager.GetString("DisposeMethodsShouldCallBaseClassDisposeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Methods Should Call Base Class Dispose.
        /// </summary>
        internal static string DisposeMethodsShouldCallBaseClassDisposeTitle {
            get {
                return ResourceManager.GetString("DisposeMethodsShouldCallBaseClassDisposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a constructor calls a virtual method, the constructor for the instance that invokes the method may not have executed..
        /// </summary>
        internal static string DoNotCallOverridableMethodsInConstructorsDescription {
            get {
                return ResourceManager.GetString("DoNotCallOverridableMethodsInConstructorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call overridable methods in constructors.
        /// </summary>
        internal static string DoNotCallOverridableMethodsInConstructorsMessage {
            get {
                return ResourceManager.GetString("DoNotCallOverridableMethodsInConstructorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not call overridable methods in constructors.
        /// </summary>
        internal static string DoNotCallOverridableMethodsInConstructorsTitle {
            get {
                return ResourceManager.GetString("DoNotCallOverridableMethodsInConstructorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not author general catch handlers in code that receives corrupted state exceptions..
        /// </summary>
        internal static string DoNotCatchCorruptedStateExceptionsInGeneralHandlersDescription {
            get {
                return ResourceManager.GetString("DoNotCatchCorruptedStateExceptionsInGeneralHandlersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not catch corrupted state exceptions in general handlers..
        /// </summary>
        internal static string DoNotCatchCorruptedStateExceptionsInGeneralHandlersMessage {
            get {
                return ResourceManager.GetString("DoNotCatchCorruptedStateExceptionsInGeneralHandlersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not catch corrupted state exceptions in general handlers..
        /// </summary>
        internal static string DoNotCatchCorruptedStateExceptionsInGeneralHandlersTitle {
            get {
                return ResourceManager.GetString("DoNotCatchCorruptedStateExceptionsInGeneralHandlersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The common language runtime initializes all fields to their default values before running the constructor. In most cases, initializing a field to its default value in a constructor is redundant, which degrades performance and adds to maintenance costs. One case where it is not redundant occurs when the constructor calls another constructor of the same class or a base class constructor and that constructor initializes the field to a non-default value. In this case, changing the value of the field back to its [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DoNotInitializeUnnecessarilyDescription {
            get {
                return ResourceManager.GetString("DoNotInitializeUnnecessarilyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not initialize unnecessarily.
        /// </summary>
        internal static string DoNotInitializeUnnecessarilyMessage {
            get {
                return ResourceManager.GetString("DoNotInitializeUnnecessarilyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not initialize unnecessarily.
        /// </summary>
        internal static string DoNotInitializeUnnecessarilyTitle {
            get {
                return ResourceManager.GetString("DoNotInitializeUnnecessarilyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object is said to have a weak identity when it can be directly accessed across application domain boundaries. A thread that tries to acquire a lock on an object that has a weak identity can be blocked by a second thread in a different application domain that has a lock on the same object..
        /// </summary>
        internal static string DoNotLockOnObjectsWithWeakIdentityDescription {
            get {
                return ResourceManager.GetString("DoNotLockOnObjectsWithWeakIdentityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not lock on objects with weak identity.
        /// </summary>
        internal static string DoNotLockOnObjectsWithWeakIdentityMessage {
            get {
                return ResourceManager.GetString("DoNotLockOnObjectsWithWeakIdentityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not lock on objects with weak identity.
        /// </summary>
        internal static string DoNotLockOnObjectsWithWeakIdentityTitle {
            get {
                return ResourceManager.GetString("DoNotLockOnObjectsWithWeakIdentityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When an exception is raised in a finally or fault clause, the new exception hides the active exception. When an exception is raised in a filter clause, the run time silently catches the exception. This makes the original error difficult to detect and debug..
        /// </summary>
        internal static string DoNotRaiseExceptionsInExceptionClausesDescription {
            get {
                return ResourceManager.GetString("DoNotRaiseExceptionsInExceptionClausesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify member {0} so that it does not raise an exception from within a fault clause. When an exception is raised from within a fault clause, the new exception hides the active exception, making the original error hard to detect and debug..
        /// </summary>
        internal static string DoNotRaiseExceptionsInExceptionClausesMessageFault {
            get {
                return ResourceManager.GetString("DoNotRaiseExceptionsInExceptionClausesMessageFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify member {0} so that it does not raise an exception from within a filter clause. When an exception is raised from within a filter clause, the runtime silently catches the exception, causing the filter to evaluate to false. This makes it hard to detect and debug errors in the filter&apos;s logic..
        /// </summary>
        internal static string DoNotRaiseExceptionsInExceptionClausesMessageFilter {
            get {
                return ResourceManager.GetString("DoNotRaiseExceptionsInExceptionClausesMessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify member {0} so that it does not raise an exception from within a finally clause. When an exception is raised from within a finally clause, the new exception hides the active exception, if present, making the original error hard to detect and debug..
        /// </summary>
        internal static string DoNotRaiseExceptionsInExceptionClausesMessageFinally {
            get {
                return ResourceManager.GetString("DoNotRaiseExceptionsInExceptionClausesMessageFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not raise exceptions in exception clauses.
        /// </summary>
        internal static string DoNotRaiseExceptionsInExceptionClausesTitle {
            get {
                return ResourceManager.GetString("DoNotRaiseExceptionsInExceptionClausesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type that is not sufficiently specific or reserved by the runtime should never be raised by user code. This makes the original error difficult to detect and debug. If this exception instance might be thrown, use a different exception type..
        /// </summary>
        internal static string DoNotRaiseReservedExceptionTypesDescription {
            get {
                return ResourceManager.GetString("DoNotRaiseReservedExceptionTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type {0} is reserved by the runtime..
        /// </summary>
        internal static string DoNotRaiseReservedExceptionTypesMessageReserved {
            get {
                return ResourceManager.GetString("DoNotRaiseReservedExceptionTypesMessageReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type {0} is not sufficiently specific..
        /// </summary>
        internal static string DoNotRaiseReservedExceptionTypesMessageTooGeneric {
            get {
                return ResourceManager.GetString("DoNotRaiseReservedExceptionTypesMessageTooGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not raise reserved exception types.
        /// </summary>
        internal static string DoNotRaiseReservedExceptionTypesTitle {
            get {
                return ResourceManager.GetString("DoNotRaiseReservedExceptionTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection is directly indexable. Going through LINQ here causes unnecessary allocations and CPU work..
        /// </summary>
        internal static string DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyDescription {
            get {
                return ResourceManager.GetString("DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyDes" +
                        "cription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use Enumerable methods on indexable collections. Instead use the collection directly.
        /// </summary>
        internal static string DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyMessage {
            get {
                return ResourceManager.GetString("DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyMes" +
                        "sage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use Enumerable methods on indexable collections. Instead use the collection directly.
        /// </summary>
        internal static string DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTitle {
            get {
                return ResourceManager.GetString("DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTit" +
                        "le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher-frequency periodic activity will keep the CPU busy and interfere with power-saving idle timers that turn off the display and hard disks..
        /// </summary>
        internal static string DoNotUseTimersThatPreventPowerStateChangesDescription {
            get {
                return ResourceManager.GetString("DoNotUseTimersThatPreventPowerStateChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use timers that prevent power state changes.
        /// </summary>
        internal static string DoNotUseTimersThatPreventPowerStateChangesMessage {
            get {
                return ResourceManager.GetString("DoNotUseTimersThatPreventPowerStateChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use timers that prevent power state changes.
        /// </summary>
        internal static string DoNotUseTimersThatPreventPowerStateChangesTitle {
            get {
                return ResourceManager.GetString("DoNotUseTimersThatPreventPowerStateChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalization must be propagated through the inheritance hierarchy. To guarantee this, types must call their base class Finalize method in their own Finalize method..
        /// </summary>
        internal static string FinalizersShouldCallBaseClassFinalizerDescription {
            get {
                return ResourceManager.GetString("FinalizersShouldCallBaseClassFinalizerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizers should call base class finalizer.
        /// </summary>
        internal static string FinalizersShouldCallBaseClassFinalizerMessage {
            get {
                return ResourceManager.GetString("FinalizersShouldCallBaseClassFinalizerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizers should call base class finalizer.
        /// </summary>
        internal static string FinalizersShouldCallBaseClassFinalizerTitle {
            get {
                return ResourceManager.GetString("FinalizersShouldCallBaseClassFinalizerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value type declares an explicit static constructor. To fix a violation of this rule, initialize all static data when it is declared and remove the static constructor..
        /// </summary>
        internal static string InitializeValueTypeStaticFieldsInlineDescription {
            get {
                return ResourceManager.GetString("InitializeValueTypeStaticFieldsInlineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize value type static fields inline.
        /// </summary>
        internal static string InitializeValueTypeStaticFieldsInlineMessage {
            get {
                return ResourceManager.GetString("InitializeValueTypeStaticFieldsInlineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize value type static fields inline.
        /// </summary>
        internal static string InitializeValueTypeStaticFieldsInlineTitle {
            get {
                return ResourceManager.GetString("InitializeValueTypeStaticFieldsInlineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format argument that is passed to System.String.Format does not contain a format item that corresponds to each object argument, or vice versa..
        /// </summary>
        internal static string ProvideCorrectArgumentsToFormattingMethodsDescription {
            get {
                return ResourceManager.GetString("ProvideCorrectArgumentsToFormattingMethodsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide correct arguments to formatting methods.
        /// </summary>
        internal static string ProvideCorrectArgumentsToFormattingMethodsMessage {
            get {
                return ResourceManager.GetString("ProvideCorrectArgumentsToFormattingMethodsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide correct arguments to formatting methods.
        /// </summary>
        internal static string ProvideCorrectArgumentsToFormattingMethodsTitle {
            get {
                return ResourceManager.GetString("ProvideCorrectArgumentsToFormattingMethodsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception is rethrown and the exception is explicitly specified in the throw statement. If an exception is rethrown by specifying the exception in the throw statement, the list of method calls between the original method that threw the exception and the current method is lost..
        /// </summary>
        internal static string RethrowToPreserveStackDetailsDescription {
            get {
                return ResourceManager.GetString("RethrowToPreserveStackDetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rethrow to preserve stack details.
        /// </summary>
        internal static string RethrowToPreserveStackDetailsMessage {
            get {
                return ResourceManager.GetString("RethrowToPreserveStackDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rethrow to preserve stack details.
        /// </summary>
        internal static string RethrowToPreserveStackDetailsTitle {
            get {
                return ResourceManager.GetString("RethrowToPreserveStackDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing strings by using the String.Length property or the String.IsNullOrEmpty method is significantly faster than using Equals..
        /// </summary>
        internal static string TestForEmptyStringsUsingStringLengthDescription {
            get {
                return ResourceManager.GetString("TestForEmptyStringsUsingStringLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the call to {0} in {1} with a check for non-null and &apos;String.Length == 0&apos;..
        /// </summary>
        internal static string TestForEmptyStringsUsingStringLengthMessageDefault {
            get {
                return ResourceManager.GetString("TestForEmptyStringsUsingStringLengthMessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the call to {0} in {1} with a call to &apos;String.IsNullOrEmpty&apos;..
        /// </summary>
        internal static string TestForEmptyStringsUsingStringLengthMessageIsNullOrEmpty {
            get {
                return ResourceManager.GetString("TestForEmptyStringsUsingStringLengthMessageIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for empty strings using string length.
        /// </summary>
        internal static string TestForEmptyStringsUsingStringLengthTitle {
            get {
                return ResourceManager.GetString("TestForEmptyStringsUsingStringLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This expression tests a value against Single.Nan or Double.Nan. Use Single.IsNan(Single) or Double.IsNan(Double) to test the value..
        /// </summary>
        internal static string TestForNaNCorrectlyDescription {
            get {
                return ResourceManager.GetString("TestForNaNCorrectlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for NaN correctly.
        /// </summary>
        internal static string TestForNaNCorrectlyMessage {
            get {
                return ResourceManager.GetString("TestForNaNCorrectlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for NaN correctly.
        /// </summary>
        internal static string TestForNaNCorrectlyTitle {
            get {
                return ResourceManager.GetString("TestForNaNCorrectlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string comparison operation that is nonlinguistic does not set the StringComparison parameter to either Ordinal or OrdinalIgnoreCase. By explicitly setting the parameter to either StringComparison.Ordinal or StringComparison.OrdinalIgnoreCase, your code often gains speed, becomes more correct, and becomes more reliable..
        /// </summary>
        internal static string UseOrdinalStringComparisonDescription {
            get {
                return ResourceManager.GetString("UseOrdinalStringComparisonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} passes &apos;{1}&apos; as the &apos;StringComparer&apos; parameter to {2}. To perform a non-linguistic comparison, specify &apos;StringComparer.Ordinal&apos; or &apos;StringComparer.OrdinalIgnoreCase&apos; instead..
        /// </summary>
        internal static string UseOrdinalStringComparisonMessageStringComparer {
            get {
                return ResourceManager.GetString("UseOrdinalStringComparisonMessageStringComparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} passes &apos;{1}&apos; as the &apos;StringComparison&apos; parameter to {2}. To perform a non-linguistic comparison, specify &apos;StringComparison.Ordinal&apos; or &apos;StringComparison.OrdinalIgnoreCase&apos; instead..
        /// </summary>
        internal static string UseOrdinalStringComparisonMessageStringComparison {
            get {
                return ResourceManager.GetString("UseOrdinalStringComparisonMessageStringComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ordinal stringcomparison.
        /// </summary>
        internal static string UseOrdinalStringComparisonTitle {
            get {
                return ResourceManager.GetString("UseOrdinalStringComparisonTitle", resourceCulture);
            }
        }
    }
}
