// <auto-generated/>

#nullable enable
using System.Reflection;


namespace TestProject
{
    /// <summary>Resources</summary>
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager? s_resourceManager;
        /// <summary>ResourceManager</summary>
        public static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));

        /// <summary>value</summary>
        public static string @Name => GetResourceString("Name")!;

    }
}
