//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileIssues {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileIssues.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delaying {0} msec between issues....
        /// </summary>
        internal static string DebugDelaying {
            get {
                return ResourceManager.GetString("DebugDelaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DependencyNone {
            get {
                return ResourceManager.GetString("DependencyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorFormat {
            get {
                return ResourceManager.GetString("ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rules inventory file &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ErrorRulesFileNotFound {
            get {
                return ResourceManager.GetString("ErrorRulesFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding label &quot;{0}&quot;....
        /// </summary>
        internal static string InfoAddingLabel {
            get {
                return ResourceManager.GetString("InfoAddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing issue #{0}....
        /// </summary>
        internal static string InfoClosingIssue {
            get {
                return ResourceManager.GetString("InfoClosingIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --dry-run option specified; issue was not actually created..
        /// </summary>
        internal static string InfoDryRunIssueNotCreated {
            get {
                return ResourceManager.GetString("InfoDryRunIssueNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --dry-run option specified; issue was not actually updated..
        /// </summary>
        internal static string InfoDryRunIssueNotUpdated {
            get {
                return ResourceManager.GetString("InfoDryRunIssueNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --dry-run option specified; labels were not actually updated..
        /// </summary>
        internal static string InfoDryRunLabelsNotUpdated {
            get {
                return ResourceManager.GetString("InfoDryRunLabelsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filing new issue for rule {0}....
        /// </summary>
        internal static string InfoFilingNewIssue {
            get {
                return ResourceManager.GetString("InfoFilingNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue #{0} created..
        /// </summary>
        internal static string InfoIssueCreated {
            get {
                return ResourceManager.GetString("InfoIssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue #{0} updated..
        /// </summary>
        internal static string InfoIssueUpdated {
            get {
                return ResourceManager.GetString("InfoIssueUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing label &quot;{0}&quot;....
        /// </summary>
        internal static string InfoRemovingLabel {
            get {
                return ResourceManager.GetString("InfoRemovingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopening issue #{0}....
        /// </summary>
        internal static string InfoReopeningIssue {
            get {
                return ResourceManager.GetString("InfoReopeningIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating issue #{0} for rule {1}....
        /// </summary>
        internal static string InfoUpdatingExistingIssue {
            get {
                return ResourceManager.GetString("InfoUpdatingExistingIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple issues exists for rule {0}: {1}.
        /// </summary>
        internal static string WarningMultipleIssuesExist {
            get {
                return ResourceManager.GetString("WarningMultipleIssuesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No area label matches the proposed analyzer &quot;{0}&quot; for rule {1}..
        /// </summary>
        internal static string WarningNoAreaAssigned {
            get {
                return ResourceManager.GetString("WarningNoAreaAssigned", resourceCulture);
            }
        }
    }
}
